baseURL = "https://docs.libp2p.io"
relativeURLs = true
languageCode = "en-us"
title = "libp2p Documentation"

theme = "hugo-theme-learn"

[params]
themeVariant = "libp2p"
disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-home'></i> libp2p.io"
url = "https://libp2p.io"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> libp2p Github"
url = "https://github.com/libp2p/libp2p"
weight = 2
