baseURL = "https://docs.libp2p.io"
relativeURLs = true
languageCode = "en-us"
title = "libp2p Documentation"
summaryLength = 20

theme = ["hugo-theme-learn"]

[params]
themeVariant = "libp2p"
disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-home'></i> libp2p.io"
url = "https://libp2p.io"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> libp2p GitHub"
url = "https://github.com/libp2p/libp2p"
weight = 2

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> libp2p Specs"
url = "https://github.com/libp2p/specs"
weight = 3

[[menu.shortcuts]]
name = "<i class='fab fa-discourse'></i> Discussion Forums"
url = "https://discuss.libp2p.io"
weight = 4

[[menu.shortcuts]]
name = "<i class='fab fa-discourse'></i> Connectivity"
url = "https://connectivity.libp2p.io"
weight = 5

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
